<a href="https://colab.research.google.com/github/condor68mihon/InformationTheory/blob/master/03_01_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Примеры

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.25')

## Игральная кость: три броска

### Выпадение четверки

In [ ]:
likelihood = np.array([1/4, 1/6, 1/8])
prior = np.array([1/3, 1/3, 1/3])

(likelihood * prior) / np.dot(likelihood, prior)

array([0.46153846, 0.30769231, 0.23076923])

### Все три броска

In [ ]:
# зададим априорную вероятность перед первым броском и
prior = np.array([1/3, 1/3, 1/3])
# результаты бросков
rolls = np.array([4, 2, 5])

# начнем бросать кость
for r in rolls:

  # зададим правдоподобие каждой из костей
  likelihood = np.array([1/4, 1/6, 1/8])

  # с тем условием, что если число больше четырех,
  if r > 4:
    # это не может быть первая кость
    likelihood[0] = 0
  # если число больше шести,
  if r > 6:
    # это не может быть вторая
    likelihood[1] = 0

  # найдем апостериорную вероятность
  posterior = (likelihood * prior) / np.dot(likelihood, prior)
  # выведем апостериорную вероятность после каждого броска
  print(posterior)
  # сделаем ее новой априорной вероятностью
  prior = posterior

[0.46153846 0.30769231 0.23076923]
[0.59016393 0.26229508 0.14754098]
[0.        0.7032967 0.2967033]


### MAP и MLE

#### Одинаковая априорная вероятность

In [ ]:
likelihood = np.array([1/4, 1/6, 1/8])
prior = np.array([1/3, 1/3, 1/3])

posterior = (likelihood * prior) / np.dot(likelihood, prior)

# найдем оценки MAP и MLE
# "+1" добавлен, чтобы нумерация костей
# начиналась с единицы, а не с нуля
MAP = np.argmax(posterior) + 1
MLE = np.argmax(likelihood) + 1

posterior, MAP, MLE

(array([0.46153846, 0.30769231, 0.23076923]), 1, 1)

#### Разная априорная вероятность

In [ ]:
likelihood = np.array([1/4, 1/6, 1/8])
prior = np.array([1/5, 2/5, 2/5])

posterior = (likelihood * prior) / np.dot(likelihood, prior)
MAP = np.argmax(posterior) + 1
MLE = np.argmax(likelihood) + 1

posterior, MAP, MLE

(array([0.3, 0.4, 0.3]), 2, 1)

## Отгадывание кости

In [ ]:
def dice_agent(prior, rolls):

  for r in rolls:

    likelihood = np.array([1/4, 1/6, 1/8, 1/12])

    if r > 4:
      likelihood[0] = 0
    if r > 6:
      likelihood[1] = 0
    if r > 8:
      likelihood[2] = 0

    posterior = (likelihood * prior) / np.dot(likelihood, prior)
    prior = posterior

  # функция будет возвращать апостериорные вероятности и MAP-оценку
  return posterior, np.argmax(posterior) + 1

Бросим первую кость (c четырьмя гранями) 5 раз

In [ ]:
prior = np.array([1/4, 1/4, 1/4, 1/4])

np.random.seed(42)
rolls = np.random.randint(1, 5, size = 5)

dice_agent(prior, rolls)

(array([0.8568595 , 0.11283747, 0.02677686, 0.00352617]), 1)

Бросим вторую кость (c шестью гранями) 3 раза

In [ ]:
prior = np.array([1/3, 1/6, 1/6, 1/3])

np.random.seed(42)
rolls = np.random.randint(1, 7, size = 3)

dice_agent(prior, rolls)

(array([0.        , 0.59813084, 0.25233645, 0.14953271]), 2)